version: '3.7'
services:
  pm2:
    container_name: pm2
    image: jordotech/ipsum_pm2:latest
    networks:
      - contenta
    ports:
      - "3000:3000"
    depends_on:
      - php
  nginx:
    container_name: nginx
    build: ./docker/nginx
    ports:
      - "8181:80"
      - "443:443"
    networks:
      - contenta
    volumes:
      - ./www:/var/www:cached
    # this ensures that nginx's upstream host "php" will always have
    # valid DNS when we're starting up
    depends_on:
      - php
  php:
    container_name: php
    #build: ./php
    image: jordotech/ipsum_php:latest
    ports:
      - "9000:9000"
    volumes:
      - ./www:/var/www:cached
    environment:
      - COLUMNS=150
      - SHELL=/bin/bash
    env_file:
      - .env
    networks:
      - contenta
  database:
    container_name: db
    build: ./database
    ports:
      - "3306:3306"
    environment:
      - COLUMNS=150
      - SHELL=/bin/bash
    volumes:
      - contenta_dbdata:/var/lib/mysql
      - ./mariadb-init:/docker-entrypoint-initdb.d # Place init .sql file(s) here.
    env_file:
      - .env
    networks:
      - contenta

volumes:
  contenta_dbdata:

networks:
  contenta:
