version: '3'
services:
  contentajs:
    container_name: contentajs
    build: ./contentajs
    volumes:
      - ./contentajs:/app
    entrypoint: ["sh", "-c", "sleep 2073600"]
    working_dir: /app
    #entrypoint: ["npm", "start"]
    networks:
      - contenta
    ports:
      - "3000:3000"
    depends_on:
      - php
  nginx:
    container_name: contenta_nginx
    build: ./nginx
    ports:
      - "8181:80"
      - "443:443"
    networks:
      - contenta
    volumes:
      - ./www:/var/www:cached
    # this ensures that nginx's upstream host "php" will always have
    # valid DNS when we're starting up
    depends_on:
      - php
  php:
    container_name: contenta_php
    build: ./php
    ports:
      - "9000:9000"
    volumes:
      - ./www:/var/www:cached
    environment:
      - COLUMNS=150
      - SHELL=/bin/bash
    env_file:
      - .env
    networks:
      - contenta
  database:
    container_name: contenta_db
    build: ./database
    ports:
      - "3306:3306"
    volumes:
      - data:/var/lib/mysql
    env_file:
      - .env
    networks:
      - contenta

volumes:
  data:

networks:
  contenta:
