version: '3.7'
services:
  contentajs:
    container_name: contentajs
    build: ./contentajs
    init: true
    volumes:
      - ./contentajs:/app
    working_dir: /app
    entrypoint: ["sh", "-c", "sleep 2073600"]
    #entrypoint: ["npm", "start"]
    #entrypoint: ["pm2-runtime", "./lib/server.js"]
    networks:
      - contenta
    ports:
      - "3000:3000"
      - "9615:9615"
    depends_on:
      - php
    environment:
      - COLUMNS=150
      - SHELL=/bin/bash
  nginx:
    container_name: contenta_nginx
    build: ./nginx
    ports:
      - "8181:80"
      - "443:443"
    networks:
      - contenta
    volumes:
      - ./www:/var/www:cached
    # this ensures that nginx's upstream host "php" will always have
    # valid DNS when we're starting up
    depends_on:
      - php
  php:
    container_name: contenta_php
    build: ./php
    ports:
      - "9000:9000"
    volumes:
      - ./www:/var/www:cached
    environment:
      - COLUMNS=150
      - SHELL=/bin/bash
    env_file:
      - .env
    networks:
      - contenta
  database:
    container_name: contenta_db
    build: ./database
    ports:
      - "3306:3306"
    environment:
      - COLUMNS=150
      - SHELL=/bin/bash
    volumes:
      - contenta_dbdata:/var/lib/mysql
      - ./mariadb-init:/docker-entrypoint-initdb.d # Place init .sql file(s) here.
    env_file:
      - .env
    networks:
      - contenta

volumes:
  contenta_dbdata:

networks:
  contenta:
