version: '3.7'
services:
  pm2:
    container_name: pm2
    image: jordotech/ipsum_pm2:latest
    networks:
      - contenta
    ports:
      - "3000:3000"
    depends_on:
      - php
    volumes:
      - ./local.yml:/app/config/local.yml
  nginx:
    container_name: nginx
    image: jordotech/ipsum_nginx:latest
    ports:
      - "8181:80"
      - "443:443"
    networks:
      - contenta
    volumes:
      - www_data:/var/www:ro
    # this ensures that nginx's upstream host "php" will always have
    # valid DNS when we're starting up
    depends_on:
      - php
  php:
    container_name: php
    image: jordotech/ipsum_php:${PHP_IMG_TAG-latest}
    ports:
      - "9000:9000"
    volumes:
      - www_data:/var/www
    environment:
      - COLUMNS=150
      - SHELL=/bin/bash
    env_file:
      - .env
    networks:
      - contenta
  database:
    container_name: db
    image: jordotech/ipsum_db:latest
    ports:
      - "3306:3306"
    environment:
      - COLUMNS=150
      - SHELL=/bin/bash
    volumes:
      - contenta_dbdata:/var/lib/mysql
      - ./mariadb-init:/docker-entrypoint-initdb.d # Place init .sql file(s) here.
    env_file:
      - .env
    networks:
      - contenta

volumes:
  contenta_dbdata:
  www_data:

networks:
  contenta:
